name: Build and Test
on: [push]

jobs:
  run:
    name: Run
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
      - run: npm ci
      - run: npm run lint -- --format junit -o reports/lint/results.xml
      - run: npm run ts:compile
      - run: npm run jest -- --ci
      - run: npm run lerna -- run test --scope=e2e-generic-test-site --stream
