name: Build and Test
on: [push]

jobs:
  run:
    name: Run
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
      - run: npm ci
      - run: npm run lint
      - run: npm run ts:compile
      - run: npm run jest -- --ci
      - uses: codecov/codecov-action@v1.0.2
        with:
          token: ${{secrets.CODECOV_TOKEN}}
          file: ./reports/coverage/clover.xml
          flags: unittests
          name: codecov-umbrella
      - name: Run e2e tests
        env:
          CYPRESS_RECORD_KEY: ${{secrets.CYPRESS_TOKEN}}
        run: npm run lerna -- run test --scope=e2e-generic-test-site --stream
